name: Android SDK Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 18.0.2+101
          distribution: 'adopt'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '31.0.0'
          ndk-version: '23.0.7599858'
          distribution: 'cmdline-tools'

      - name: Check code warnings
        run: ./gradlew lintDebug

      - name: Build and Test
        run: |
          ./gradlew assembleDebug testDebug

# 目前不需要 build 出 apk
#      - name: Upload artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: app-debug
#          path: app/build/outputs/apk/debug/app-debug.apk
