name: Build and upload Android library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: /opt/android-sdk-linux
      PATH: /opt/gradle/bin:${PATH}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
          uses: actions/setup-java@v3
          with:
            java-version: 18.0.2+101
            distribution: 'adopt'

      - name: Set up Android SDK
          uses: android-actions/setup-android@v2
          with:
            sdk-version: '31.0.0'
            ndk-version: '23.0.7599858'
            distribution: 'cmdline-tools'

      - name: Check code warnings
          run: ./gradlew lintDebug

      - name: Build and Test
          run: |
            ./gradlew assembleDebug testDebug

      - name: Build Android library
        run: ./gradlew :fugle_realtime_lib:assembleRelease

      - name: Upload Android library artifact
        uses: actions/upload-artifact@v2
        with:
          name: library-release
          path: app/build/outputs/aar/library-release.aar
