name: Build and upload Android library

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: /opt/android-sdk-linux
      PATH: /opt/gradle/bin:${PATH}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '31'
          emulator-version: '30.8.4'
          arch: 'x86'
          script-parameters: '--install "platform-tools"'

      - name: Build Android library
        run: ./gradlew :fugle_realtime_lib:assembleRelease

      - name: Upload Android library artifact
        uses: actions/upload-artifact@v2
        with:
          name: library-release
          path: app/build/outputs/aar/library-release.aar
